### ISSUE TITLE
Missing Tweets

### ISSUE THREAD

**Issue by davidlimpo** [Jefferson-Henrique/GetOldTweets#14]
Hello mate,

Thanks for sharing your project!
I'm using it in order to get all tweets posted by some users but it seems not working quite well. There are some tweets that can be accessed through a browser that arent when using this lib.

For instance, in a user with 1800 tweets, I only get 866 tweets. This seems to be a bit random because I didnt find any similarities in the missed tweets. 

Do you have any suggestion to fix this problem?

Thanks! :)

**Comment by davidlimpo** [comment]
I was trying to debug the problem and I found something that can be important:

I tried to get the tweets from a specific user that has posted the following tweets in her timeline: "A B C D E F G"
By comparing the tweets returned by running this project and the tweets posted in user's timeline, I have spoted that D F and G are missing.

The .json that is received in the HttpGet doesnt miss any tweet, i.e, if you analyze the file you can realize that A B C D E F and G are present.

After this line:
`JSONObject json = new JSONObject(getURLResponse(criteria.getUsername(), criteria.getSince(), criteria.getUntil(), criteria.getQuerySearch(), refreshCursor));
`

If you print `json` you can detect that D F and G are not there anymore. So, by creating that JSONObject we are losing some tweets.

I hope this helps,
David

**Comment by Jefferson-Henrique** [comment]
Hello, very nice, I will take a look what you said about json. I know this problem, I didn't go deep because when run a test on twitter itself I saw different responses. You can test go to user's timeline as you did and compare the results with twitter advanced search, putting "from:specific_user" on search input.

**Comment by davidlimpo** [comment]
Well, thats not the only reason for the missing tweets. In some cases (I believe the most frequent) the JSON file downloaded from the URL simply doesnt contain the missing tweets.

Any suggestion?

Thanks!

**Comment by Jefferson-Henrique** [comment]
As the tool uses twitter advanced search it can only provide at least the same information that can be seen on the browser, but for a specific user you change the source, so instead of look at twitter advanced search you go through a user's timeline, this way you can get all tweets there, the logic about getting new tweets programatically should be very similar. The problem with this approach is that you don't have some parameters that twitter search provides, like "since" and "until".

**Comment by davidlimpo** [comment]
How can I find the URL for the JSON of a specific user timeline? I really have no idea.

Can you help me with that? In order to finish my masters thesis, I really need to get a lot of tweets from a lot of users.

**Comment by Jefferson-Henrique** [comment]
Change the line that set an URL in the method getURLReponse. You can replace for this one:

String url = String.format("https://twitter.com/i/profiles/show/%s/timeline?max_position=%s", username, scrollCursor == null ? "" : scrollCursor);

**Comment by davidlimpo** [comment]
Thanks for your help!

I made a few changes and combined those two URL's. I created a pull request so everyone can use this approach.
